//! Terminal User Interface (TUI) management module.
//!
//! This module provides the [`Tui`] struct, which manages all terminal I/O operations,
//! event collection, and rendering coordination. It acts as the bridge between the
//! raw terminal and the application's event loop.
//!
//! # Architecture
//!
//! The TUI layer uses **ratatui** for rendering and **crossterm** for terminal control.
//! It runs two concurrent loops:
//!
//! 1. **Event Collection Loop**: Captures keyboard, mouse, and resize events
//! 2. **Timer Loops**: Generate Tick (logic updates) and Render (draw) events
//!
//! ```text
//! ┌────────────────────────────────────────────────────┐
//! │                   Tui Manager                       │
//! │                                                     │
//! │  ┌──────────────────────────────────────────────┐ │
//! │  │         Event Collection Task                │ │
//! │  │  ┌────────────┐  ┌────────────┐             │ │
//! │  │  │ Crossterm  │  │   Timers   │             │ │
//! │  │  │  Events    │  │ Tick/Render│             │ │
//! │  │  └─────┬──────┘  └─────┬──────┘             │ │
//! │  │        │                │                     │ │
//! │  │        └────────┬───────┘                     │ │
//! │  │                 ▼                             │ │
//! │  │          event_tx (mpsc)                      │ │
//! │  └──────────────────┬───────────────────────────┘ │
//! │                     │                              │
//! │                     ▼                              │
//! │              event_rx (mpsc)                       │
//! │                     │                              │
//! │                     ▼                              │
//! │              App Event Loop                        │
//! └────────────────────────────────────────────────────┘
//! ```
//!
//! # Event Types
//!
//! The [`Event`] enum represents all possible terminal events:
//! - **Key**: Keyboard input (only KeyPress events, not release)
//! - **Mouse**: Mouse movements and clicks
//! - **Resize**: Terminal size changes
//! - **Tick**: Logic update signal (rate-limited)
//! - **Render**: Draw signal (rate-limited)
//! - **Paste**: Bracketed paste events
//! - **Focus**: Terminal focus gained/lost
//!
//! # Bounded Channels
//!
//! The TUI uses a **bounded channel with capacity 100** for events. This prevents
//! memory exhaustion during event bursts (e.g., window resize storms). If the
//! buffer fills, events are silently dropped using `try_send`.
//!
//! # Graceful Shutdown
//!
//! The TUI implements proper cleanup via [`Drop`]:
//! - Cancels the event collection task
//! - Restores terminal to normal mode
//! - Shows cursor and exits alternate screen
//! - Handles cleanup errors gracefully

use std::{
  ops::{Deref, DerefMut},
  time::Duration,
};

use color_eyre::eyre::Result;
use crossterm::{
  cursor,
  event::{
    DisableBracketedPaste, DisableMouseCapture, EnableBracketedPaste, EnableMouseCapture, Event as CrosstermEvent,
    KeyEvent, KeyEventKind, MouseEvent,
  },
  terminal::{EnterAlternateScreen, LeaveAlternateScreen},
};
use futures::{FutureExt, StreamExt};
use ratatui::backend::CrosstermBackend as Backend;
use serde::{Deserialize, Serialize};
use tokio::{
  sync::mpsc::{self, Receiver, Sender},
  task::JoinHandle,
};
use tokio_util::sync::CancellationToken;

/// Type alias for stdout used as the terminal backend.
pub type IO = std::io::Stdout;

/// Returns a handle to stdout for terminal operations.
pub fn io() -> IO {
  std::io::stdout()
}

/// Type alias for ratatui's Frame type used in rendering.
pub type Frame<'a> = ratatui::Frame<'a>;

/// Terminal events that can be received by the application.
///
/// These events are generated by the TUI's event collection task and sent
/// to the application's event loop for processing.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub enum Event {
  /// Initial event sent when the TUI starts
  Init,
  /// Request to quit the application
  Quit,
  /// An error occurred in event processing
  Error,
  /// The terminal/event stream was closed
  Closed,
  /// Logic update tick (rate-limited by tick_rate)
  Tick,
  /// Render update signal (rate-limited by frame_rate)
  Render,
  /// Terminal gained focus
  FocusGained,
  /// Terminal lost focus
  FocusLost,
  /// Bracketed paste event with pasted content
  Paste(String),
  /// Keyboard event (only KeyPress, not release)
  Key(KeyEvent),
  /// Mouse event (movement, clicks, scroll)
  Mouse(MouseEvent),
  /// Terminal was resized to new dimensions (width, height)
  Resize(u16, u16),
}

/// The Terminal User Interface coordinator.
///
/// This struct manages the terminal state, event collection, and provides
/// an interface for the application to interact with the terminal.
///
/// # Fields
///
/// * `terminal` - The ratatui terminal instance for rendering
/// * `task` - Background task handling event collection
/// * `cancellation_token` - Token to signal task cancellation
/// * `event_rx` - Receiver for terminal events
/// * `event_tx` - Sender for terminal events (cloned to task)
/// * `frame_rate` - Render updates per second
/// * `tick_rate` - Logic updates per second
/// * `mouse` - Whether mouse capture is enabled
/// * `paste` - Whether bracketed paste is enabled
pub struct Tui {
  pub terminal: ratatui::Terminal<Backend<IO>>,
  pub task: JoinHandle<()>,
  pub cancellation_token: CancellationToken,
  pub event_rx: Receiver<Event>,
  pub event_tx: Sender<Event>,
  pub frame_rate: f64,
  pub tick_rate: f64,
  pub mouse: bool,
  pub paste: bool,
}

impl Tui {
  pub fn new() -> Result<Self> {
    let tick_rate = 4.0;
    let frame_rate = 60.0;
    let terminal = ratatui::Terminal::new(Backend::new(io()))?;
    // Use bounded channel with capacity of 100 for high-frequency UI events
    // This prevents memory exhaustion during event bursts
    let (event_tx, event_rx) = mpsc::channel(100);
    let cancellation_token = CancellationToken::new();
    let task = tokio::spawn(async {});
    let mouse = false;
    let paste = false;
    Ok(Self { terminal, task, cancellation_token, event_rx, event_tx, frame_rate, tick_rate, mouse, paste })
  }

  pub fn tick_rate(mut self, tick_rate: f64) -> Self {
    self.tick_rate = tick_rate;
    self
  }

  pub fn frame_rate(mut self, frame_rate: f64) -> Self {
    self.frame_rate = frame_rate;
    self
  }

  pub fn mouse(mut self, mouse: bool) -> Self {
    self.mouse = mouse;
    self
  }

  pub fn paste(mut self, paste: bool) -> Self {
    self.paste = paste;
    self
  }

  pub fn start(&mut self) {
    let tick_delay = std::time::Duration::from_secs_f64(1.0 / self.tick_rate);
    let render_delay = std::time::Duration::from_secs_f64(1.0 / self.frame_rate);
    self.cancel();
    self.cancellation_token = CancellationToken::new();
    let _cancellation_token = self.cancellation_token.clone();
    let _event_tx = self.event_tx.clone();
    self.task = tokio::spawn(async move {
      let mut reader = crossterm::event::EventStream::new();
      let mut tick_interval = tokio::time::interval(tick_delay);
      let mut render_interval = tokio::time::interval(render_delay);
      // Send init event; if this fails, the receiver is already dropped
      if _event_tx.try_send(Event::Init).is_err() {
        return;
      }
      loop {
        let tick_delay = tick_interval.tick();
        let render_delay = render_interval.tick();
        let crossterm_event = reader.next().fuse();
        tokio::select! {
          _ = _cancellation_token.cancelled() => {
            break;
          }
          maybe_event = crossterm_event => {
            match maybe_event {
              Some(Ok(evt)) => {
                match evt {
                  CrosstermEvent::Key(key) => {
                    if key.kind == KeyEventKind::Press {
                      // Ignore send errors - channel may be full or receiver dropped
                      let _ = _event_tx.try_send(Event::Key(key));
                    }
                  },
                  CrosstermEvent::Mouse(mouse) => {
                    let _ = _event_tx.try_send(Event::Mouse(mouse));
                  },
                  CrosstermEvent::Resize(x, y) => {
                    let _ = _event_tx.try_send(Event::Resize(x, y));
                  },
                  CrosstermEvent::FocusLost => {
                    let _ = _event_tx.try_send(Event::FocusLost);
                  },
                  CrosstermEvent::FocusGained => {
                    let _ = _event_tx.try_send(Event::FocusGained);
                  },
                  CrosstermEvent::Paste(s) => {
                    let _ = _event_tx.try_send(Event::Paste(s));
                  },
                }
              }
              Some(Err(_)) => {
                let _ = _event_tx.try_send(Event::Error);
              }
              None => {},
            }
          },
          _ = tick_delay => {
              let _ = _event_tx.try_send(Event::Tick);
          },
          _ = render_delay => {
              let _ = _event_tx.try_send(Event::Render);
          },
        }
      }
    });
  }

  pub fn stop(&self) -> Result<()> {
    self.cancel();
    let mut counter = 0;
    while !self.task.is_finished() {
      std::thread::sleep(Duration::from_millis(1));
      counter += 1;
      if counter > 50 {
        self.task.abort();
      }
      if counter > 100 {
        log::error!(
          "TUI event task did not stop gracefully within 100ms timeout. \
          This may indicate the event loop is blocked or unresponsive."
        );
        break;
      }
    }
    Ok(())
  }

  pub fn enter(&mut self) -> Result<()> {
    crossterm::terminal::enable_raw_mode()?;
    crossterm::execute!(io(), EnterAlternateScreen, cursor::Hide)?;
    if self.mouse {
      crossterm::execute!(io(), EnableMouseCapture)?;
    }
    if self.paste {
      crossterm::execute!(io(), EnableBracketedPaste)?;
    }
    self.start();
    Ok(())
  }

  pub fn exit(&mut self) -> Result<()> {
    self.stop()?;
    if crossterm::terminal::is_raw_mode_enabled()? {
      self.flush()?;
      if self.paste {
        crossterm::execute!(io(), DisableBracketedPaste)?;
      }
      if self.mouse {
        crossterm::execute!(io(), DisableMouseCapture)?;
      }
      crossterm::execute!(io(), LeaveAlternateScreen, cursor::Show)?;
      crossterm::terminal::disable_raw_mode()?;
    }
    Ok(())
  }

  pub fn cancel(&self) {
    self.cancellation_token.cancel();
  }

  pub fn suspend(&mut self) -> Result<()> {
    self.exit()?;
    #[cfg(not(windows))]
    signal_hook::low_level::raise(signal_hook::consts::signal::SIGTSTP)?;
    Ok(())
  }

  pub fn resume(&mut self) -> Result<()> {
    self.enter()?;
    Ok(())
  }

  pub async fn next(&mut self) -> Option<Event> {
    self.event_rx.recv().await
  }
}

impl Deref for Tui {
  type Target = ratatui::Terminal<Backend<IO>>;

  fn deref(&self) -> &Self::Target {
    &self.terminal
  }
}

impl DerefMut for Tui {
  fn deref_mut(&mut self) -> &mut Self::Target {
    &mut self.terminal
  }
}

impl Drop for Tui {
  fn drop(&mut self) {
    if let Err(e) = self.exit() {
      eprintln!("Error during TUI cleanup: {}", e);
    }
  }
}
